"""Prompt templates for the content creation agents."""

from .audience import PERSONA_SYSTEM_PROMPT
from .image import (
    IMAGE_PLACEMENT_SYSTEM,
    IMAGE_QUERIES_SYSTEM,
    IMAGE_SUGGESTIONS_SYSTEM,
)
from .researcher import ANALYZE_TOPIC_SYSTEM, RESEARCH_BRIEF_SYSTEM
from .writer import (
    META_DESCRIPTION_SYSTEM,
    OUTLINE_SYSTEM,
    TAGS_SYSTEM,
    WRITE_ARTICLE_SYSTEM,
    WRITE_SECTION_SYSTEM,
)

__all__ = [
    "PERSONA_SYSTEM_PROMPT",
    "ANALYZE_TOPIC_SYSTEM",
    "RESEARCH_BRIEF_SYSTEM",
    "OUTLINE_SYSTEM",
    "WRITE_SECTION_SYSTEM",
    "WRITE_ARTICLE_SYSTEM",
    "META_DESCRIPTION_SYSTEM",
    "TAGS_SYSTEM",
    "IMAGE_QUERIES_SYSTEM",
    "IMAGE_SUGGESTIONS_SYSTEM",
    "IMAGE_PLACEMENT_SYSTEM",
]
