"""Prompt templates for all agents."""

from .audience import PERSONA_SYSTEM_PROMPT
from .image import (
    IMAGE_PLACEMENT_SYSTEM_PROMPT,
    IMAGE_QUERIES_SYSTEM_PROMPT,
    IMAGE_SUGGESTIONS_SYSTEM_PROMPT,
)
from .research import ANALYZE_TOPIC_SYSTEM_PROMPT, RESEARCH_BRIEF_SYSTEM_PROMPT
from .writer import (
    ARTICLE_SYSTEM_PROMPT_TEMPLATE,
    META_DESCRIPTION_SYSTEM_PROMPT,
    OUTLINE_SYSTEM_PROMPT_TEMPLATE,
    SECTION_SYSTEM_PROMPT,
    TAGS_SYSTEM_PROMPT,
)

__all__ = [
    "PERSONA_SYSTEM_PROMPT",
    "ANALYZE_TOPIC_SYSTEM_PROMPT",
    "RESEARCH_BRIEF_SYSTEM_PROMPT",
    "OUTLINE_SYSTEM_PROMPT_TEMPLATE",
    "SECTION_SYSTEM_PROMPT",
    "ARTICLE_SYSTEM_PROMPT_TEMPLATE",
    "META_DESCRIPTION_SYSTEM_PROMPT",
    "TAGS_SYSTEM_PROMPT",
    "IMAGE_QUERIES_SYSTEM_PROMPT",
    "IMAGE_SUGGESTIONS_SYSTEM_PROMPT",
    "IMAGE_PLACEMENT_SYSTEM_PROMPT",
]
